CREATE TABLE IF NOT EXISTS NEWSLETTER (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE NFT_DISCOUNT (
    id SERIAL PRIMARY KEY,
    nft VARCHAR(255) NOT NULL,
    discount VARCHAR(50) NOT NULL
);
